### PR TITLE
add array_interpolate_linear process

### PR DESCRIPTION
**Pull request by zcernigoj**
https://git.sinergise.com/team-6/openeo-platform/-/issues/97

docs: https://docs.openeo.cloud/processes/?#array_interpolate_linear

A return type in the docs is `number|null` but there is nothing about propagating `null` if the array is `null` or empty (like for some of the other processes). So, I'm not sure.

### CODE REVIEW

**Comment by zcernigoj** [comment]
A return type in the docs is `number|null` but there is nothing about propagating `null` if the array is `null` (like for some of the other processes). So, I'm not sure.

**Comment by dgostencnik** [comment]
I think the return type should be `array<number|null>`. For empty array I'd assume empty array is returned, for null probably null. Perhaps open an issue for that in openeo-processes repo

**Review by dgostencnik — APPROVED** [review]

**Comment by zcernigoj** [comment]
> I think the return type should be `array<number|null>`. For empty array I'd assume empty array is returned, for null probably null. Perhaps open an issue for that in openeo-processes repo

opened an issue: https://github.com/Open-EO/openeo-processes/issues/333

**Comment by zcernigoj** [comment]
> > I think the return type should be `array<number|null>`. For empty array I'd assume empty array is returned, for null probably null. Perhaps open an issue for that in openeo-processes repo
> 
> opened an issue: [Open-EO/openeo-processes#333](https://github.com/Open-EO/openeo-processes/issues/333)

Nothing to change as it already behaves as it should.

**Pull request merged**
